version: '2'

services:
  postgres:
    container_name: postgres_container
    image: 'postgres:9.5'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/sideby'
    volumes_from:
    - box

  box:
    image: busybox
    volumes:
      - /box

volumes:
  redis:
  postgres:
  box:
