default: &default
  adapter: postgresql
  encoding: unicode
  host: 'postgres'
  port: 5432
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: 'sideby_development'
test:
  <<: *default
  database: 'sideby_test'
production:
  <<: *default
  database: 'sideby_production'
