default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sideby_development

test:
  <<: *default
  database: sideby_test
#
production:
  <<: *default
  database: sideby_production
  username: postgresql
  password: <%= ENV['DSDS_DATABASE_PASSWORD'] %>
